### ISSUE TITLE
Unhandled rejection when changing grid sort order

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-angular1#54] opened 2017-04-28 15:41 UTC
Bug appears on Locations and Locations Vehicles screens:

angular.js:14362 Possibly unhandled rejection: canceled

**Comment by JVanderford** [comment] 2017-06-14 16:59
Looks like this is related to the Grid UI not supporting the current version of Angular we are using.  We can supress ALL  unhandled rejections , but that would potentially hide other errors

https://github.com/angular-ui/ui-grid/issues/5890

**Comment by JVanderford** [comment] 2017-06-14 17:12
This was resolved in ui-grid version 4.0.3 and I've confirmed this fixes the issue and still passes all tests.  I don't want to branch and PR this fix till we dicuss what version we want to update though.  The current version is 4.0.6 so I'm not sure where we want to update to of those options

**Comment by BWortman** [comment] 2017-06-14 17:29
Hi @JVanderford - if the latest seems to have no adverse effects let's update to that one.

**Closed** 2017-06-15 13:36 UTC
Labels: bug
